version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: |
            DISABLE_SPRING=true bundle exec rails test
  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws cli
          command:  |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: build image
          command:  |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -t $ECR_URI:$CIRCLE_SHA1 -t $ECR_URI:latest --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY} --build-arg RAILS_ENV=production .
      - run:
          name: push docker image
          command:  |
            docker push $ECR_URI:$CIRCLE_SHA1
            docker push $ECR_URI:latest
workflows:
  version: 2.1
  test:
    jobs:
      - build
      - build_image:
          requires:
            - build
          filters:
            branches:
              only: main